# Generated by Django 3.2.4 on 2021-11-30 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_skills'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Skills',
            new_name='Skill',
        ),
    ]
