# Generated by Django 3.2.4 on 2021-12-01 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20211130_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_budget',
            field=models.IntegerField(blank=True, default=250000, null=True),
        ),
    ]
