# Generated by Django 3.2.4 on 2021-12-02 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_auto_20211202_2158'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
