# Generated by Django 3.2.4 on 2021-12-02 21:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_delete_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='total_budget',
            field=models.IntegerField(blank=True, default=250000, null=True, validators=[django.core.validators.MaxValueValidator(250000), django.core.validators.MinValueValidator(1)]),
        ),
    ]
