# Generated by Django 3.2.9 on 2021-12-05 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_donation'),
        ('projects', '0017_alter_project_options'),
    ]

    operations = [
    ]
