# Generated by Django 3.2.9 on 2021-12-06 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_merge_0013_donation_0017_alter_project_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donation',
            name='id',
        ),
        migrations.AddField(
            model_name='project',
            name='donation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.donation'),
        ),
    ]
