# Generated by Django 3.2.9 on 2021-12-06 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20211206_0328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='donation',
        ),
        migrations.AddField(
            model_name='donation',
            name='id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
    ]
